# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-devel
warnings_are_errors: true
sudo: false
cache: packages

addons:
  apt:
    packages:
      - libnetcdf-dev
#      - netcdf-bin # libnetcdf-dev doesn't contain nc-config in ubuntu 12.04 (in 16.04 it is part of libnetcdf-dev)
      - libhdf5-dev
#      - texlive-latex-recommended
#      - texlive-fonts-extra

# In general the r-travis script automatically dump the logs after failure but
# because of a bug in travis the output is often truncated. See
# https://github.com/travis-ci/travis-ci/issues/6018
after_failure: sleep 10

notifications:
  email:
    recipients: yann.guitton@gmail.com
    on_failure: change
    on_success: change